services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: jenkins-server
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock # Comunicação com o Docker do Host
      - .:/home/projeto # Mapeia sua pasta atual para dentro do Jenkins (opcional, mas ajuda)
    restart: unless-stopped

  api-pagamentos:
    image: api-pagamentos:latest
    container_name: api-pagamentos-prod
    ports:
      - "3000:3000"
    restart: unless-stopped

volumes:
  jenkins_home:
